import { Nav, Footer } from "@/app/components/nav";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white flex flex-col">
      <Nav />
      <div className="max-w-2xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-8">Terms of service</h1>
        <div className="space-y-6 text-white/60 text-sm leading-relaxed">
          <p>Last updated: June 2026</p>

          <h2 className="text-white font-semibold text-base mt-8">For developers</h2>
          <p>By installing and using the spincome hook, you agree to display ads in your terminal during Claude Code sessions. You earn 50% of the CPM revenue generated by impressions on your machine. Earnings are tracked in milli-cents for precision and can be withdrawn via Stripe once your account is connected.</p>
          <p>You may disable ads at any time by running &quot;npx @brozarti/spincome disable&quot; or setting enabled: false in your config. Disabling stops all ad display and earning immediately.</p>

          <h2 className="text-white font-semibold text-base mt-8">For advertisers</h2>
          <p>Campaign budgets are charged via Stripe Checkout before activation. Impressions are billed using a second-price (Vickrey) auction — you pay one cent above the next highest bid, never more than your max CPM. Clicks are billed at 50x the winning impression rate.</p>
          <p>Campaigns can be paused or exhausted. Unused budget is not automatically refunded — contact support for refund requests on unused campaign balance.</p>

          <h2 className="text-white font-semibold text-base mt-8">Referral program</h2>
          <p>Referrers earn 10% of each referred developer&apos;s impression earnings indefinitely. This is paid from the platform&apos;s share, not from the referred developer&apos;s earnings. Abuse of the referral system (self-referral fraud, bot accounts) will result in account termination.</p>

          <h2 className="text-white font-semibold text-base mt-8">Payouts</h2>
          <p>Developer payouts are processed automatically every Monday via Stripe transfers for any balance above $0.50. Manual withdrawals from the dashboard require a $10 minimum. The platform is not responsible for Stripe processing delays.</p>

          <h2 className="text-white font-semibold text-base mt-8">Content policy</h2>
          <p>Ads must not contain misleading claims, malware links, adult content, or illegal material. Spincome reserves the right to reject or remove campaigns that violate these guidelines.</p>

          <h2 className="text-white font-semibold text-base mt-8">Limitation of liability</h2>
          <p>Spincome is provided &quot;as is&quot; without warranty. We are not liable for lost earnings, service interruptions, or third-party actions. Maximum liability is limited to the amount paid or earned through the platform in the preceding 30 days.</p>

          <h2 className="text-white font-semibold text-base mt-8">Contact</h2>
          <p>Questions: <a href="mailto:spincome.io@gmail.com" className="text-emerald-400 hover:text-emerald-300">spincome.io@gmail.com</a></p>
        </div>
      </div>
      <Footer />
    </main>
  );
}
